// Code generated by protoc-gen-go.
// source: common/common.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	common/common.proto

It has these top-level messages:
	PartSetHeader
	BlockID
	Header
	Block
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PartSetHeader struct {
	Total uint32 `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Hash  []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *PartSetHeader) Reset()                    { *m = PartSetHeader{} }
func (m *PartSetHeader) String() string            { return proto.CompactTextString(m) }
func (*PartSetHeader) ProtoMessage()               {}
func (*PartSetHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BlockID struct {
	Hash        []byte         `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	PartsHeader *PartSetHeader `protobuf:"bytes,2,opt,name=partsHeader" json:"partsHeader,omitempty"`
}

func (m *BlockID) Reset()                    { *m = BlockID{} }
func (m *BlockID) String() string            { return proto.CompactTextString(m) }
func (*BlockID) ProtoMessage()               {}
func (*BlockID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BlockID) GetPartsHeader() *PartSetHeader {
	if m != nil {
		return m.PartsHeader
	}
	return nil
}

type Header struct {
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Block struct {
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*PartSetHeader)(nil), "common.PartSetHeader")
	proto.RegisterType((*BlockID)(nil), "common.BlockID")
	proto.RegisterType((*Header)(nil), "common.Header")
	proto.RegisterType((*Block)(nil), "common.Block")
}

func init() { proto.RegisterFile("common/common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x92,
	0x25, 0x17, 0x6f, 0x40, 0x62, 0x51, 0x49, 0x70, 0x6a, 0x89, 0x47, 0x6a, 0x62, 0x4a, 0x6a, 0x91,
	0x90, 0x08, 0x17, 0x6b, 0x49, 0x7e, 0x49, 0x62, 0x8e, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6f, 0x10,
	0x84, 0x23, 0x24, 0xc4, 0xc5, 0x92, 0x91, 0x58, 0x9c, 0x21, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x13,
	0x04, 0x66, 0x2b, 0x85, 0x71, 0xb1, 0x3b, 0xe5, 0xe4, 0x27, 0x67, 0x7b, 0xba, 0xc0, 0xa5, 0x19,
	0x11, 0xd2, 0x42, 0xe6, 0x5c, 0xdc, 0x05, 0x89, 0x45, 0x25, 0xc5, 0x10, 0x73, 0xc1, 0x3a, 0xb9,
	0x8d, 0x44, 0xf5, 0xa0, 0xae, 0x40, 0xb1, 0x34, 0x08, 0x59, 0xa5, 0x12, 0x07, 0x17, 0x1b, 0x94,
	0xc5, 0xce, 0xc5, 0x0a, 0xb6, 0xc1, 0x29, 0x96, 0x4b, 0x33, 0xbf, 0x28, 0x5d, 0xcf, 0xb2, 0x24,
	0x23, 0x39, 0x23, 0x31, 0x33, 0x4f, 0x2f, 0x09, 0x24, 0x0a, 0x66, 0xea, 0x16, 0x18, 0x15, 0x40,
	0xbc, 0x54, 0x0c, 0x35, 0x3a, 0xca, 0x20, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x09, 0xc4, 0xd5, 0x87,
	0xe9, 0xd0, 0x47, 0xd5, 0xa1, 0x0f, 0xd1, 0x01, 0x0d, 0x92, 0x24, 0x36, 0x30, 0xd7, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0xe8, 0x1f, 0xbf, 0xbb, 0x2a, 0x01, 0x00, 0x00,
}
