// Code generated by protoc-gen-go.
// source: consensus/consensus.proto
// DO NOT EDIT!

/*
Package consensus is a generated protocol buffer package.

It is generated from these files:
	consensus/consensus.proto

It has these top-level messages:
	NewRoundStepMessage
	BitArray
	CommitStepMessage
	Proposal
	ProposalMessage
	ProposalPOLMessage
	SimpleProof
	Part
	BlockPartMessage
	Vote
	VoteMessage
	HasVoteMessage
	VoteSetMaj23Message
	VoteSetBitsMessage
	Heartbeat
	ProposalHeartbeatMessage
*/
package consensus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/9thchain/blockchain-p2p/protos/common"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RoundStepType int32

const (
	RoundStepType_Unknown       RoundStepType = 0
	RoundStepType_NewHeight     RoundStepType = 1
	RoundStepType_NewRound      RoundStepType = 2
	RoundStepType_Propose       RoundStepType = 3
	RoundStepType_Prevote       RoundStepType = 4
	RoundStepType_PrevoteWait   RoundStepType = 5
	RoundStepType_Precommit     RoundStepType = 6
	RoundStepType_PrecommitWait RoundStepType = 7
	RoundStepType_Commit        RoundStepType = 8
)

var RoundStepType_name = map[int32]string{
	0: "Unknown",
	1: "NewHeight",
	2: "NewRound",
	3: "Propose",
	4: "Prevote",
	5: "PrevoteWait",
	6: "Precommit",
	7: "PrecommitWait",
	8: "Commit",
}
var RoundStepType_value = map[string]int32{
	"Unknown":       0,
	"NewHeight":     1,
	"NewRound":      2,
	"Propose":       3,
	"Prevote":       4,
	"PrevoteWait":   5,
	"Precommit":     6,
	"PrecommitWait": 7,
	"Commit":        8,
}

func (x RoundStepType) String() string {
	return proto.EnumName(RoundStepType_name, int32(x))
}
func (RoundStepType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type VoteType int32

const (
	VoteType_UnVote    VoteType = 0
	VoteType_PreVote   VoteType = 1
	VoteType_PreCommit VoteType = 2
)

var VoteType_name = map[int32]string{
	0: "UnVote",
	1: "PreVote",
	2: "PreCommit",
}
var VoteType_value = map[string]int32{
	"UnVote":    0,
	"PreVote":   1,
	"PreCommit": 2,
}

func (x VoteType) String() string {
	return proto.EnumName(VoteType_name, int32(x))
}
func (VoteType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type NewRoundStepMessage struct {
	Height                uint64        `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	Round                 uint32        `protobuf:"varint,2,opt,name=round" json:"round,omitempty"`
	Step                  RoundStepType `protobuf:"varint,3,opt,name=step,enum=consensus.RoundStepType" json:"step,omitempty"`
	SecondsSinceStartTime uint32        `protobuf:"varint,4,opt,name=secondsSinceStartTime" json:"secondsSinceStartTime,omitempty"`
	LastCommitRound       uint32        `protobuf:"varint,5,opt,name=lastCommitRound" json:"lastCommitRound,omitempty"`
}

func (m *NewRoundStepMessage) Reset()                    { *m = NewRoundStepMessage{} }
func (m *NewRoundStepMessage) String() string            { return proto.CompactTextString(m) }
func (*NewRoundStepMessage) ProtoMessage()               {}
func (*NewRoundStepMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BitArray struct {
	Bits  uint32   `protobuf:"varint,1,opt,name=bits" json:"bits,omitempty"`
	Elems []uint64 `protobuf:"varint,2,rep,packed,name=elems" json:"elems,omitempty"`
}

func (m *BitArray) Reset()                    { *m = BitArray{} }
func (m *BitArray) String() string            { return proto.CompactTextString(m) }
func (*BitArray) ProtoMessage()               {}
func (*BitArray) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CommitStepMessage struct {
	Height          uint64                `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	BlockPartHeader *common.PartSetHeader `protobuf:"bytes,2,opt,name=blockPartHeader" json:"blockPartHeader,omitempty"`
	BlockParts      *BitArray             `protobuf:"bytes,3,opt,name=blockParts" json:"blockParts,omitempty"`
}

func (m *CommitStepMessage) Reset()                    { *m = CommitStepMessage{} }
func (m *CommitStepMessage) String() string            { return proto.CompactTextString(m) }
func (*CommitStepMessage) ProtoMessage()               {}
func (*CommitStepMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CommitStepMessage) GetBlockPartHeader() *common.PartSetHeader {
	if m != nil {
		return m.BlockPartHeader
	}
	return nil
}

func (m *CommitStepMessage) GetBlockParts() *BitArray {
	if m != nil {
		return m.BlockParts
	}
	return nil
}

type Proposal struct {
	Height           uint64                     `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	Round            uint32                     `protobuf:"varint,2,opt,name=round" json:"round,omitempty"`
	Timestamp        *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	BlockPartsHeader *common.PartSetHeader      `protobuf:"bytes,4,opt,name=blockPartsHeader" json:"blockPartsHeader,omitempty"`
	POLRound         int32                      `protobuf:"varint,5,opt,name=POLRound" json:"POLRound,omitempty"`
	Signatuure       []byte                     `protobuf:"bytes,6,opt,name=signatuure,proto3" json:"signatuure,omitempty"`
}

func (m *Proposal) Reset()                    { *m = Proposal{} }
func (m *Proposal) String() string            { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()               {}
func (*Proposal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Proposal) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Proposal) GetBlockPartsHeader() *common.PartSetHeader {
	if m != nil {
		return m.BlockPartsHeader
	}
	return nil
}

type ProposalMessage struct {
	Proposal *Proposal `protobuf:"bytes,1,opt,name=Proposal" json:"Proposal,omitempty"`
}

func (m *ProposalMessage) Reset()                    { *m = ProposalMessage{} }
func (m *ProposalMessage) String() string            { return proto.CompactTextString(m) }
func (*ProposalMessage) ProtoMessage()               {}
func (*ProposalMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ProposalMessage) GetProposal() *Proposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

type ProposalPOLMessage struct {
	Height           uint64    `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	ProposalPOLRound uint32    `protobuf:"varint,2,opt,name=proposalPOLRound" json:"proposalPOLRound,omitempty"`
	ProposalPOL      *BitArray `protobuf:"bytes,3,opt,name=proposalPOL" json:"proposalPOL,omitempty"`
}

func (m *ProposalPOLMessage) Reset()                    { *m = ProposalPOLMessage{} }
func (m *ProposalPOLMessage) String() string            { return proto.CompactTextString(m) }
func (*ProposalPOLMessage) ProtoMessage()               {}
func (*ProposalPOLMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ProposalPOLMessage) GetProposalPOL() *BitArray {
	if m != nil {
		return m.ProposalPOL
	}
	return nil
}

type SimpleProof struct {
	Aunts [][]byte `protobuf:"bytes,1,rep,name=aunts,proto3" json:"aunts,omitempty"`
}

func (m *SimpleProof) Reset()                    { *m = SimpleProof{} }
func (m *SimpleProof) String() string            { return proto.CompactTextString(m) }
func (*SimpleProof) ProtoMessage()               {}
func (*SimpleProof) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type Part struct {
	Index uint64       `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Bytes []byte       `protobuf:"bytes,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Proof *SimpleProof `protobuf:"bytes,3,opt,name=proof" json:"proof,omitempty"`
	Hash  []byte       `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *Part) Reset()                    { *m = Part{} }
func (m *Part) String() string            { return proto.CompactTextString(m) }
func (*Part) ProtoMessage()               {}
func (*Part) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Part) GetProof() *SimpleProof {
	if m != nil {
		return m.Proof
	}
	return nil
}

type BlockPartMessage struct {
	Height uint64 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	Round  uint32 `protobuf:"varint,2,opt,name=round" json:"round,omitempty"`
	Part   *Part  `protobuf:"bytes,3,opt,name=part" json:"part,omitempty"`
}

func (m *BlockPartMessage) Reset()                    { *m = BlockPartMessage{} }
func (m *BlockPartMessage) String() string            { return proto.CompactTextString(m) }
func (*BlockPartMessage) ProtoMessage()               {}
func (*BlockPartMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BlockPartMessage) GetPart() *Part {
	if m != nil {
		return m.Part
	}
	return nil
}

type Vote struct {
	ValidatorAddress []byte                     `protobuf:"bytes,1,opt,name=validatorAddress,proto3" json:"validatorAddress,omitempty"`
	ValidatorIndex   uint32                     `protobuf:"varint,2,opt,name=validatorIndex" json:"validatorIndex,omitempty"`
	Height           uint64                     `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	Round            uint32                     `protobuf:"varint,4,opt,name=round" json:"round,omitempty"`
	Timestamp        *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=timestamp" json:"timestamp,omitempty"`
	Type             VoteType                   `protobuf:"varint,6,opt,name=type,enum=consensus.VoteType" json:"type,omitempty"`
	BlockID          *common.BlockID            `protobuf:"bytes,7,opt,name=blockID" json:"blockID,omitempty"`
	Signature        []byte                     `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Vote) Reset()                    { *m = Vote{} }
func (m *Vote) String() string            { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()               {}
func (*Vote) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Vote) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Vote) GetBlockID() *common.BlockID {
	if m != nil {
		return m.BlockID
	}
	return nil
}

type VoteMessage struct {
	Vote *Vote `protobuf:"bytes,1,opt,name=vote" json:"vote,omitempty"`
}

func (m *VoteMessage) Reset()                    { *m = VoteMessage{} }
func (m *VoteMessage) String() string            { return proto.CompactTextString(m) }
func (*VoteMessage) ProtoMessage()               {}
func (*VoteMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *VoteMessage) GetVote() *Vote {
	if m != nil {
		return m.Vote
	}
	return nil
}

type HasVoteMessage struct {
	Height uint64   `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	Round  uint32   `protobuf:"varint,2,opt,name=round" json:"round,omitempty"`
	Type   VoteType `protobuf:"varint,3,opt,name=type,enum=consensus.VoteType" json:"type,omitempty"`
	Index  uint32   `protobuf:"varint,4,opt,name=index" json:"index,omitempty"`
}

func (m *HasVoteMessage) Reset()                    { *m = HasVoteMessage{} }
func (m *HasVoteMessage) String() string            { return proto.CompactTextString(m) }
func (*HasVoteMessage) ProtoMessage()               {}
func (*HasVoteMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type VoteSetMaj23Message struct {
	Height  uint64          `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	Round   uint32          `protobuf:"varint,2,opt,name=round" json:"round,omitempty"`
	Type    VoteType        `protobuf:"varint,3,opt,name=type,enum=consensus.VoteType" json:"type,omitempty"`
	BlockID *common.BlockID `protobuf:"bytes,4,opt,name=blockID" json:"blockID,omitempty"`
}

func (m *VoteSetMaj23Message) Reset()                    { *m = VoteSetMaj23Message{} }
func (m *VoteSetMaj23Message) String() string            { return proto.CompactTextString(m) }
func (*VoteSetMaj23Message) ProtoMessage()               {}
func (*VoteSetMaj23Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *VoteSetMaj23Message) GetBlockID() *common.BlockID {
	if m != nil {
		return m.BlockID
	}
	return nil
}

type VoteSetBitsMessage struct {
	Height  uint64          `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	Round   uint32          `protobuf:"varint,2,opt,name=round" json:"round,omitempty"`
	Type    VoteType        `protobuf:"varint,3,opt,name=type,enum=consensus.VoteType" json:"type,omitempty"`
	BlockID *common.BlockID `protobuf:"bytes,4,opt,name=blockID" json:"blockID,omitempty"`
	Votes   *BitArray       `protobuf:"bytes,5,opt,name=votes" json:"votes,omitempty"`
}

func (m *VoteSetBitsMessage) Reset()                    { *m = VoteSetBitsMessage{} }
func (m *VoteSetBitsMessage) String() string            { return proto.CompactTextString(m) }
func (*VoteSetBitsMessage) ProtoMessage()               {}
func (*VoteSetBitsMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *VoteSetBitsMessage) GetBlockID() *common.BlockID {
	if m != nil {
		return m.BlockID
	}
	return nil
}

func (m *VoteSetBitsMessage) GetVotes() *BitArray {
	if m != nil {
		return m.Votes
	}
	return nil
}

type Heartbeat struct {
	ValidatorAddress []byte `protobuf:"bytes,1,opt,name=validatorAddress,proto3" json:"validatorAddress,omitempty"`
	ValidatorIndex   uint32 `protobuf:"varint,2,opt,name=validatorIndex" json:"validatorIndex,omitempty"`
	Height           uint64 `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	Round            uint32 `protobuf:"varint,4,opt,name=round" json:"round,omitempty"`
	Sequence         uint32 `protobuf:"varint,5,opt,name=sequence" json:"sequence,omitempty"`
	Signature        []byte `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Heartbeat) Reset()                    { *m = Heartbeat{} }
func (m *Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()               {}
func (*Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type ProposalHeartbeatMessage struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat" json:"heartbeat,omitempty"`
}

func (m *ProposalHeartbeatMessage) Reset()                    { *m = ProposalHeartbeatMessage{} }
func (m *ProposalHeartbeatMessage) String() string            { return proto.CompactTextString(m) }
func (*ProposalHeartbeatMessage) ProtoMessage()               {}
func (*ProposalHeartbeatMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ProposalHeartbeatMessage) GetHeartbeat() *Heartbeat {
	if m != nil {
		return m.Heartbeat
	}
	return nil
}

func init() {
	proto.RegisterType((*NewRoundStepMessage)(nil), "consensus.NewRoundStepMessage")
	proto.RegisterType((*BitArray)(nil), "consensus.BitArray")
	proto.RegisterType((*CommitStepMessage)(nil), "consensus.CommitStepMessage")
	proto.RegisterType((*Proposal)(nil), "consensus.Proposal")
	proto.RegisterType((*ProposalMessage)(nil), "consensus.ProposalMessage")
	proto.RegisterType((*ProposalPOLMessage)(nil), "consensus.ProposalPOLMessage")
	proto.RegisterType((*SimpleProof)(nil), "consensus.SimpleProof")
	proto.RegisterType((*Part)(nil), "consensus.Part")
	proto.RegisterType((*BlockPartMessage)(nil), "consensus.BlockPartMessage")
	proto.RegisterType((*Vote)(nil), "consensus.Vote")
	proto.RegisterType((*VoteMessage)(nil), "consensus.VoteMessage")
	proto.RegisterType((*HasVoteMessage)(nil), "consensus.HasVoteMessage")
	proto.RegisterType((*VoteSetMaj23Message)(nil), "consensus.VoteSetMaj23Message")
	proto.RegisterType((*VoteSetBitsMessage)(nil), "consensus.VoteSetBitsMessage")
	proto.RegisterType((*Heartbeat)(nil), "consensus.Heartbeat")
	proto.RegisterType((*ProposalHeartbeatMessage)(nil), "consensus.ProposalHeartbeatMessage")
	proto.RegisterEnum("consensus.RoundStepType", RoundStepType_name, RoundStepType_value)
	proto.RegisterEnum("consensus.VoteType", VoteType_name, VoteType_value)
}

func init() { proto.RegisterFile("consensus/consensus.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 954 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xee, 0xda, 0x6b, 0xc7, 0x3e, 0xb6, 0xe3, 0xed, 0xa4, 0xad, 0x16, 0x0b, 0x81, 0xb5, 0x91,
	0xc0, 0x8d, 0x82, 0x2d, 0x39, 0x45, 0x82, 0x2b, 0x14, 0xc3, 0x45, 0x2a, 0xb5, 0xa9, 0x35, 0x4e,
	0x41, 0xe2, 0x6e, 0x6c, 0x9f, 0xda, 0x4b, 0xed, 0x9d, 0x65, 0x67, 0xdc, 0x90, 0x0b, 0x9e, 0x01,
	0x89, 0x1b, 0xae, 0x79, 0x07, 0x5e, 0x80, 0x2b, 0xae, 0x79, 0x14, 0xde, 0x00, 0xcd, 0xcf, 0xfe,
	0xd8, 0x09, 0x29, 0x41, 0x42, 0xea, 0x95, 0xf7, 0x3b, 0xe7, 0xdb, 0xd9, 0x73, 0xbe, 0xef, 0xcc,
	0x78, 0xe0, 0xbd, 0x19, 0x8f, 0x04, 0x46, 0x62, 0x23, 0x06, 0xd9, 0x53, 0x3f, 0x4e, 0xb8, 0xe4,
	0xa4, 0x9e, 0x05, 0x3a, 0x07, 0x33, 0xbe, 0x5e, 0xf3, 0x68, 0x60, 0x7e, 0x4c, 0xbe, 0xf3, 0xe1,
	0x82, 0xf3, 0xc5, 0x0a, 0x07, 0x1a, 0x4d, 0x37, 0xaf, 0x06, 0x32, 0x5c, 0xa3, 0x90, 0x6c, 0x1d,
	0x1b, 0x42, 0xf0, 0xa7, 0x03, 0x07, 0xe7, 0x78, 0x49, 0xf9, 0x26, 0x9a, 0x4f, 0x24, 0xc6, 0xcf,
	0x51, 0x08, 0xb6, 0x40, 0xf2, 0x08, 0xaa, 0x4b, 0x0c, 0x17, 0x4b, 0xe9, 0x3b, 0x5d, 0xa7, 0xe7,
	0x52, 0x8b, 0xc8, 0x03, 0xa8, 0x24, 0x8a, 0xeb, 0x97, 0xba, 0x4e, 0xaf, 0x45, 0x0d, 0x20, 0xc7,
	0xe0, 0x0a, 0x89, 0xb1, 0x5f, 0xee, 0x3a, 0xbd, 0xfd, 0xa1, 0xdf, 0xcf, 0xcb, 0xcc, 0x16, 0xbe,
	0xb8, 0x8a, 0x91, 0x6a, 0x16, 0x79, 0x02, 0x0f, 0x05, 0xce, 0x78, 0x34, 0x17, 0x93, 0x30, 0x9a,
	0xe1, 0x44, 0xb2, 0x44, 0x5e, 0x84, 0x6b, 0xf4, 0x5d, 0xbd, 0xe6, 0xcd, 0x49, 0xd2, 0x83, 0xf6,
	0x8a, 0x09, 0xf9, 0x25, 0x5f, 0xaf, 0x43, 0xa9, 0x97, 0xf5, 0x2b, 0x9a, 0xbf, 0x1b, 0x0e, 0x9e,
	0x40, 0x6d, 0x14, 0xca, 0xd3, 0x24, 0x61, 0x57, 0x84, 0x80, 0x3b, 0x0d, 0xa5, 0xd0, 0x5d, 0xb4,
	0xa8, 0x7e, 0x56, 0x3d, 0xe0, 0x0a, 0xd7, 0xc2, 0x2f, 0x75, 0xcb, 0x3d, 0x97, 0x1a, 0x10, 0xfc,
	0xea, 0xc0, 0x7d, 0xb3, 0xca, 0xbf, 0xd1, 0xe1, 0x0b, 0x68, 0x4f, 0x57, 0x7c, 0xf6, 0x7a, 0xcc,
	0x12, 0x79, 0x86, 0x6c, 0x8e, 0x89, 0x56, 0xa4, 0x31, 0x7c, 0xd8, 0xb7, 0x06, 0xa8, 0xcc, 0x04,
	0x6d, 0x92, 0xee, 0xb2, 0xc9, 0x09, 0x40, 0x16, 0x12, 0x5a, 0xb8, 0xc6, 0xf0, 0xa0, 0x20, 0x5c,
	0xda, 0x01, 0x2d, 0xd0, 0x82, 0xbf, 0x1c, 0xa8, 0x8d, 0x13, 0x1e, 0x73, 0xc1, 0x56, 0x77, 0xb4,
	0xe8, 0x33, 0xa8, 0x67, 0xde, 0xdb, 0xcf, 0x75, 0xfa, 0x66, 0x3a, 0xfa, 0xe9, 0x74, 0xf4, 0x2f,
	0x52, 0x06, 0xcd, 0xc9, 0xe4, 0x14, 0xbc, 0xbc, 0x04, 0xdb, 0xab, 0x7b, 0x5b, 0xaf, 0xd7, 0xe8,
	0xa4, 0x03, 0xb5, 0xf1, 0x8b, 0x67, 0xb9, 0x69, 0x15, 0x9a, 0x61, 0xf2, 0x01, 0x80, 0x08, 0x17,
	0x11, 0x93, 0x9b, 0x4d, 0x82, 0x7e, 0xb5, 0xeb, 0xf4, 0x9a, 0xb4, 0x10, 0x09, 0x46, 0xd0, 0x4e,
	0x5b, 0x4e, 0x4d, 0x19, 0xe4, 0x2a, 0xe8, 0xde, 0xb7, 0x95, 0x4b, 0x53, 0x34, 0x23, 0x05, 0x3f,
	0x39, 0x40, 0x52, 0x30, 0x7e, 0xf1, 0xec, 0x6d, 0xe6, 0x1e, 0x81, 0x17, 0xe7, 0x6c, 0x5a, 0x10,
	0xf3, 0x5a, 0x9c, 0x7c, 0x0a, 0x8d, 0x42, 0xec, 0x36, 0x23, 0x8b, 0xbc, 0xe0, 0x10, 0x1a, 0x93,
	0x70, 0x1d, 0xaf, 0x70, 0x9c, 0x70, 0xfe, 0x4a, 0x79, 0xc6, 0x36, 0x91, 0x9e, 0xd3, 0x72, 0xaf,
	0x49, 0x0d, 0x08, 0x24, 0xb8, 0x4a, 0x45, 0x95, 0x0d, 0xa3, 0x39, 0xfe, 0x60, 0xcb, 0x34, 0x40,
	0x45, 0xa7, 0x57, 0x12, 0x85, 0x2e, 0xad, 0x49, 0x0d, 0x20, 0xc7, 0x50, 0x89, 0xd5, 0x92, 0xb6,
	0x92, 0x47, 0x85, 0x4a, 0x0a, 0x1f, 0xa4, 0x86, 0xa4, 0xb6, 0xc7, 0x92, 0x89, 0xa5, 0xf6, 0xb3,
	0x49, 0xf5, 0x73, 0x80, 0xe0, 0x8d, 0x52, 0x03, 0xff, 0xdb, 0x71, 0x70, 0x08, 0x6e, 0xcc, 0x12,
	0x69, 0x4b, 0x68, 0x17, 0xbd, 0x61, 0x89, 0xa4, 0x3a, 0x19, 0xfc, 0x56, 0x02, 0xf7, 0x6b, 0x2e,
	0x51, 0xa9, 0xfd, 0x86, 0xad, 0xc2, 0x39, 0x93, 0x3c, 0x39, 0x9d, 0xcf, 0x13, 0x14, 0x66, 0xbb,
	0x36, 0xe9, 0xb5, 0x38, 0xf9, 0x08, 0xf6, 0xb3, 0xd8, 0x53, 0x2d, 0x89, 0xf9, 0xf0, 0x4e, 0xb4,
	0x50, 0x6f, 0xf9, 0xe6, 0x7a, 0xdd, 0x7f, 0xdc, 0x1b, 0x95, 0xbb, 0xec, 0x8d, 0x8f, 0xc1, 0x95,
	0x57, 0xb1, 0x19, 0xdb, 0xfd, 0x2d, 0xdb, 0x55, 0x6b, 0xe6, 0xcc, 0x53, 0x04, 0xf2, 0x18, 0xf6,
	0xf4, 0xae, 0x78, 0xfa, 0x95, 0xbf, 0x97, 0xa9, 0xa2, 0xf7, 0xce, 0xc8, 0x84, 0x69, 0x9a, 0x27,
	0xef, 0x43, 0xdd, 0x8e, 0x7f, 0x82, 0x7e, 0x4d, 0x0b, 0x91, 0x07, 0x82, 0x21, 0x34, 0xd4, 0xd2,
	0xa9, 0x31, 0x87, 0xe0, 0xbe, 0xe1, 0x12, 0xed, 0x36, 0x68, 0xef, 0x14, 0x40, 0x75, 0x32, 0xf8,
	0x11, 0xf6, 0xcf, 0x98, 0x28, 0xbe, 0x76, 0x37, 0x3f, 0xd3, 0x2e, 0xcb, 0x6f, 0xeb, 0x32, 0x1b,
	0x54, 0x2b, 0xaf, 0x06, 0xc1, 0x2f, 0x0e, 0x1c, 0x28, 0xe2, 0x04, 0xe5, 0x73, 0xf6, 0xdd, 0xf0,
	0xe4, 0x7f, 0x2e, 0xa2, 0x20, 0xb5, 0x7b, 0xbb, 0xd4, 0xc1, 0xef, 0x0e, 0x10, 0x5b, 0xd9, 0x28,
	0x94, 0xe2, 0x9d, 0x29, 0x8c, 0x3c, 0x86, 0x8a, 0x72, 0x4e, 0xd8, 0x69, 0xbc, 0xf1, 0x3c, 0x31,
	0x8c, 0xe0, 0x0f, 0x07, 0xea, 0x67, 0xc8, 0x12, 0x39, 0x45, 0x26, 0xdf, 0x81, 0xcd, 0xd4, 0x81,
	0x9a, 0xc0, 0xef, 0x37, 0x18, 0xcd, 0xd0, 0xfe, 0x41, 0x67, 0x78, 0x7b, 0xb4, 0xab, 0xbb, 0xa3,
	0x7d, 0x0e, 0x7e, 0x7a, 0x48, 0x67, 0x0d, 0xa5, 0x96, 0x0c, 0xa1, 0xbe, 0x4c, 0x63, 0x76, 0xd8,
	0x1f, 0x14, 0x44, 0xc9, 0xf8, 0x34, 0xa7, 0x1d, 0xfd, 0xec, 0x40, 0x6b, 0xeb, 0xfe, 0x41, 0x1a,
	0xb0, 0xf7, 0x32, 0x7a, 0x1d, 0xf1, 0xcb, 0xc8, 0xbb, 0x47, 0x5a, 0x50, 0x3f, 0xc7, 0xcb, 0x33,
	0xdd, 0x8b, 0xe7, 0x90, 0x26, 0xd4, 0xd2, 0x8b, 0x90, 0x57, 0x52, 0x4c, 0x53, 0x0b, 0x7a, 0x65,
	0x03, 0x50, 0xc9, 0xed, 0xb9, 0xa4, 0x0d, 0x0d, 0x0b, 0xbe, 0x61, 0xa1, 0xf4, 0x2a, 0x6a, 0x9d,
	0x71, 0x82, 0x33, 0x7d, 0x75, 0xf0, 0xaa, 0xe4, 0x3e, 0xb4, 0x32, 0xa8, 0x19, 0x7b, 0x04, 0xa0,
	0x6a, 0x6e, 0x16, 0x5e, 0xed, 0x68, 0x08, 0xb5, 0x74, 0x2c, 0x54, 0xfc, 0x65, 0xa4, 0x90, 0x77,
	0xcf, 0x7e, 0x43, 0x03, 0xc7, 0x2e, 0x69, 0xdf, 0x29, 0x8d, 0x66, 0x70, 0xcc, 0x93, 0x45, 0xff,
	0x73, 0xb9, 0x9c, 0x2d, 0x59, 0x18, 0xf5, 0xf5, 0x94, 0xe8, 0xc7, 0x4f, 0xe2, 0xa1, 0xbd, 0xc9,
	0x89, 0x5c, 0x8d, 0x6f, 0x4f, 0x16, 0xa1, 0x5c, 0x6e, 0xa6, 0x6a, 0xba, 0x06, 0xe9, 0x4b, 0x83,
	0xed, 0x97, 0xcc, 0x8d, 0xb0, 0x70, 0xa1, 0x9c, 0x56, 0x75, 0xe4, 0xe4, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x5b, 0x11, 0x36, 0xf3, 0x6e, 0x0a, 0x00, 0x00,
}
